-- tables:
-- SELECT * FROM olist.olist_products_dataset LIMIT 10	
-- SELECT * FROM olist.olist_order_items_dataset LIMIT 10	
-- SELECT * FROM olist.olist_marketing_qualified_leads_dataset LIMIT 10	
-- SELECT * FROM olist.olist_closed_deals_dataset LIMIT 10	

-- measures and dimentions:
-- pd olist.olist_products_dataset --> 
-- oi olist.olist_order_items_dataset -->
-- mqld olist.olist_marketing_qualified_leads_dataset -->
-- cdd olist.olist_closed_deals_dataset -->
